# Rate limiter config — private instance, no limits needed
[botdetection]
trusted_proxies = []
ipv4_prefix = 32
ipv6_prefix = 48

[botdetection.ip_limit]
link_token = false

[botdetection.ip_lists]
block_ip = []
pass_ip = []
